AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Events
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      
  FoodsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Foods
      AttributeDefinitions:
        - AttributeName: foodId
          AttributeType: S
      KeySchema:
        - AttributeName: foodId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    
  VotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Votes
      AttributeDefinitions:
        - AttributeName: voteId
          AttributeType: S
      KeySchema:
        - AttributeName: voteId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  EventsTable:
    Description: "The newly created events table"
    Value:
      Ref: EventsTable
  FoodsTable:
    Description: "The newly created foods table"
    Value:
      Ref: FoodsTable
  VotesTable:
    Description: "The newly created food events table"
    Value:
      Ref: VotesTable
